In [89]:
#importing the required libraries for selenium

!pip install selenium
import selenium
from selenium import webdriver

Requirement already satisfied: selenium in c:\users\bovi\anaconda3\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\bovi\anaconda3\lib\site-packages (from selenium) (1.26.4)

In [94]:
#conecting to the web driver
driver=webdriver.Chrome("chromedriver.exe")

In [21]:
#accessing to the url naukri
url="https://www.naukri.com/"
driver.get(url)

In [22]:
#finding the html element for search box
search=driver.find_element_by_id('qsb-keyword-sugg')
search

In [23]:
#Writing "Data Analyst" in the search box
search.send_keys("Data Analyst")

In [24]:
#finding the html element for search box for location
search_loc=driver.find_element_by_id('qsb-location-sugg')
search_loc.send_keys("Bangalore")

In [25]:
#finding the html element for search button
search_btn=driver.find_element_by_xpath("//button[@class='btn']")

In [26]:
search_btn.click()

In [27]:
#let's extract all the tags having the job-titles
titles_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
titles_tags

[<selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="b5b425f1-769a-4084-b4ef-5e0c653145cf")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="33410f03-75e5-4c24-809b-b06d161188c7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="50945d2d-15ab-4faa-8b84-5664e0cc631a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="ab7294cb-6c9b-4b77-af50-9adb4a16d8ea")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="38038641-87d2-474b-a503-13b57355b9d1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="f0da23a6-b4a3-41f3-b1b1-8378980754d9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="61128202-742c-4044-9d62-e13f50fd22e7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="0c1efa48-6193-43d3-9a2c-8a72145daa7a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="256b04dd-0834-42fe-af12-c17d68d0b6f9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="bf18c91b-d9da-4206-8694-9d3fd663eda1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="aec9202b-db37-4b81-b162-b2f7f14c9e8e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="0c346b44-9731-4e16-9903-8493342a8b2b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="3f1230f1-99d5-4e72-a985-7c12f29635bf")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="4ad08be1-f5a2-49c2-89da-fbc5f2b4c408")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="4c35b7b5-d42b-4fc9-a3ca-78eaf061ff77")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="54a012dd-ed47-464f-96dc-330f405955bd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="a6a19fe8-ffb7-40a6-8ab4-1dc7ac946db9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="bc2ebeab-23af-4c9b-b56a-34ea24298b57")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="d102ecca-38a1-45ae-bc7f-4419945442f5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="a1ac42f9-b05e-4a92-a54f-bb5064c37fda")>]

In [28]:
#now we will run a loop to iterate over the tags extracted above and extract the title text inside them
job_titles=[]
for i in titles_tags:
    job_titles.append(i.text)
job_titles

['Business Data Analyst',
 'Business Data Analyst',
 'Senior Data Analyst IDAM Services',
 'Data Analyst/Sr.Data Engineer',
 'SENIOR DATA ANALYST',
 'Business Data Analyst - Google Data Studio & SQL',
 'Senior Data Analyst IN4',
 'Tcs Hiring For Senior Data Analyst (bfsi domain)',
 'Data Analyst - Python/SQL',
 'Executive Data Analyst',
 'Tcs Hiring For MDM (master data management) Data Analyst (bfsi domain)',
 'Senior Data Analyst',
 'Systems and Data Analyst, Safety and Provisioning',
 'Data Analyst with SQL',
 'Data Analyst',
 'Sr Data Analyst',
 'Sr Analyst - Data Analysis',
 'Business Data Analyst - MIS & Reporting',
 'Data Analyst',
 'Data Analyst']

In [29]:
#now we will extract all the tags having the companies names
companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies_tags

[<selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="2160a43a-cd61-443d-b68d-e932cc8603e7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="4f6ac0f7-fd50-476d-b745-5f94a423ba26")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="e990d441-47de-4076-92f3-942a7d2ec7e9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="9b1aa558-2c9c-46aa-9e40-faa249ce7137")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="1cf39ef2-03d4-41c2-bf79-29518b6a7631")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="29809d5c-cd18-43ee-9e8d-e976b0a0d393")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="806bca3d-efbf-4269-bf63-06cead392711")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="463f2bb6-8a5b-407d-ba5a-ed85b0521e27")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="d577ba8f-a89c-4e55-b10d-beaab25541fd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="5b4e3053-025a-4575-a744-96a91500fdc9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="86a0c1d8-0e24-4689-ac71-7bb27dadf911")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="dfcd24a4-f9e3-4ee9-907a-1f82d8fc12ac")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="76db0efa-b0c2-419b-8fc0-f13435e99460")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="eac46f91-7b1d-43dd-b808-94d8d20591a5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="638a8a24-12fb-469a-9350-6c25c0dcc672")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="5a1d37c1-4eb7-4767-8b77-ab96b6552cab")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="1aecddbf-39d9-440f-8c50-8fb014c9125e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="a30415c3-d206-457b-a471-3a9c4075d170")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="583d4389-3863-4b56-b950-9e9d2f30d4f1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="7b2cb0e8-7084-4647-8c79-c16217c8175e")>]

In [30]:
#now we will run a loop to iterate over the tags extracted above and extract the company text inside them

companies_names=[]
for i in companies_tags:
    companies_names.append(i.text)
companies_names

['Trigent Software',
 'Trigent Software',
 'GlaxoSmithKline Pharmaceuticals Limited',
 'SYREN TECHNOLOGIES PRIVATE LIMITED',
 'McAfee Software (India) Pvt. Ltd',
 'AVE-Promagne',
 'Walmart Labs',
 'Tata Consultancy Services Ltd.',
 'Affine',
 'Gokaldas Exports Ltd',
 'Tata Consultancy Services Ltd.',
 'Virtusa Consulting Services Pvt Ltd',
 'AECOM India Private Limited',
 'Wipro Limited',
 'IBM India Pvt. Limited',
 'Empower Retirement',
 'Tesco Bengaluru',
 'INTERTRUST GROUP',
 'Edge Executive Search Pvt. Ltd.',
 'Morgan Stanley Advantage Services']

In [31]:
#now getting the tags for experience required
experience_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']//span")
experience_tags

[<selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="976c2b04-f691-4e6e-8b07-0c02d2e38fa3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="e47715f5-dada-4725-9208-db09c45cbffd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="be473f4b-7fae-47b0-a40c-821c3493e353")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="b28d7025-0002-48b5-a72a-09c5211d6377")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="010de2b9-6225-4ec5-8f77-99eb744ed6ae")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="149125c9-13b0-4fed-864a-8970277f0950")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="b63092d7-b3b3-4f0b-ab67-c4882b2914e6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="7e319264-b021-4b03-a42a-ba04c5ed5a65")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="e9baf384-8c54-4456-b0c2-954b8f960ce6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="4f0379b7-9220-4593-85f6-d0199cfaa0ab")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="886a6c99-9b67-4658-8d77-08763fdce05d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="b20e4139-eaac-4bcf-89fb-f03666bf6f41")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="e539b520-3393-453a-aa43-17aac04d99b3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="2699c0d4-c100-4d18-baf3-772d03cf7ce1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="848aab83-13d7-4d28-a78a-6af1c07230dc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="4f693aa4-015b-4539-b616-7e92a24b7db8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="7a99a742-b766-4b9e-9dd9-46b272bbaa3c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="2118c041-8e73-4599-8039-d1d451a1071d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="3e43bfc2-53e9-4372-a54f-b530fdab94ca")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="ce6096b8-4cce-41c8-8e10-db1dec310fe7")>]

In [32]:
##now we will run a loop to iterate over the tags extracted above and extract the experience text inside them

experience_required=[]
for i in experience_tags:
    experience_required.append(i.text)
experience_required

['5-10 Yrs',
 '5-10 Yrs',
 '4-8 Yrs',
 '4-9 Yrs',
 '6-8 Yrs',
 '3-8 Yrs',
 '8-10 Yrs',
 '6-11 Yrs',
 '3-5 Yrs',
 '0-3 Yrs',
 '6-11 Yrs',
 '8-12 Yrs',
 '2-7 Yrs',
 '3-5 Yrs',
 '1-4 Yrs',
 '5-8 Yrs',
 '2-4 Yrs',
 '3-8 Yrs',
 '0-2 Yrs',
 '5-10 Yrs']

In [33]:
#now getting the tags for location
location_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']//span")
location_tags

[<selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="eb950aaf-bef9-4592-b55c-83de7d8b8726")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="65985f00-c2f1-49ad-bb04-cdbaa46957b7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="58d4a2f2-05ad-4a3a-b81b-e129814c9f48")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="14b46ac7-7899-438d-bf1e-efb54f484ba8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="e5b741bc-3c76-45ae-8f1b-3d593cf06e6a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="3109a1dc-06cb-4c02-a006-b82e0136889a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="76e2653b-7a71-462c-a695-d671e3029020")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="5b4e6a1c-a031-4d63-964d-e32e530c658a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="3fd058e1-414f-439d-8202-86ea00320fef")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="f4ed66eb-38a8-4a04-a240-c990e807c311")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="f9073a02-a791-48c4-bd08-5dec2313311c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="85b28789-e054-4fa2-8bfd-0bcabf372dc8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="88107dc1-373c-4f3e-83c6-cb7af01243bd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="ba6af4bc-ab10-4fef-8a37-e61ed4f37e74")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="aa80a95b-4f8a-43f7-9473-4633f62d5e8c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="32c65502-e561-41a1-a919-ca60f0d5a5cc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="4f680b4d-9b58-4800-afe8-51862a68f689")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="d145b0bf-c1bc-4b13-bd6f-6a5b9f7c09a0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="2f711a56-782f-4215-8051-3e7a62a0d298")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="a1264eaf-f017-49f4-99c2-2fdd2014a5e2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="2190be24-6371-4b0c-ac81-f66dea85e3b3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="2ef96054f6061f34b4a6b018ed9dfa44", element="0fe4138a-a2f1-4ae7-bfb8-9af85f929007")>]

In [34]:
#now we will run a loop to iterate over the tags extracted above and extract the location text inside them

location=[]
for i in location_tags:
    location.append(i.text)
location

['Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Hyderabad/Secunderabad, Chennai, Bangalore/Bengaluru',
 '(WFH during Covid)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Chennai, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Chennai, Bangalore/Bengaluru',
 'Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram, Chennai, Bangalore/Bengaluru, Mumbai (All Areas)',
 '(WFH during Covid)',
 'Bangalore/Bengaluru',
 'Noida, Gurgaon/Gurugram, Bangalore/Bengaluru',
 'Bengaluru/Bangalore',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Mumbai, Bangalore/Bengaluru',
 'Pune, Bangalore/Bengaluru, Mumbai (All Areas)',
 'Bangalore/Bengaluru']

In [35]:
#creating the dataframe with all the scrapped data
import pandas as pd
jobs=pd.DataFrame({})
jobs['Title']=job_titles[0:10]
jobs['Location']=location[0:10]
jobs['Company']=companies_names[0:10]
jobs['Experience']=experience_required[0:10]

In [36]:
jobs ##Q1 Data Analyst Banglore

,Title,Location,Company,Experience
0,Business Data Analyst,Bangalore/Bengaluru,Trigent Software,5-10 Yrs
1,Business Data Analyst,Bangalore/Bengaluru,Trigent Software,5-10 Yrs
2,Senior Data Analyst IDAM Services,Bangalore/Bengaluru,GlaxoSmithKline Pharmaceuticals Limited,4-8 Yrs
3,Data Analyst/Sr.Data Engineer,"Hyderabad/Secunderabad, Chennai, Bangalore/Ben...",SYREN TECHNOLOGIES PRIVATE LIMITED,4-9 Yrs
4,SENIOR DATA ANALYST,(WFH during Covid),McAfee Software (India) Pvt. Ltd,6-8 Yrs
5,Business Data Analyst - Google Data Studio & SQL,Bangalore/Bengaluru,AVE-Promagne,3-8 Yrs
6,Senior Data Analyst IN4,Bangalore/Bengaluru,Walmart Labs,8-10 Yrs
7,Tcs Hiring For Senior Data Analyst (bfsi domain),Bangalore/Bengaluru,Tata Consultancy Services Ltd.,6-11 Yrs
8,Data Analyst - Python/SQL,"Chennai, Bangalore/Bengaluru",Affine,3-5 Yrs
9,Executive Data Analyst,Bangalore/Bengaluru,Gokaldas Exports Ltd,0-3 Yrs

In [95]:
#Q2
#accesing the url, doing the corresponding search input and clicking on the search button
url="https://www.naukri.com/"
driver.get(url)
search=driver.find_element_by_id('qsb-keyword-sugg')
search.send_keys("Data Scientist")
search_loc=driver.find_element_by_id('qsb-location-sugg')
search_loc.send_keys("Bangalore")
search_btn=driver.find_element_by_xpath("//button[@class='btn']")
search_btn.click()

In [ ]:
#getting tags for titles,companies,location) and then we will run a loop to iterate over the tags extracted above and extract the titles,companies,location text inside them

titles_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
job_titles=[]
for i in titles_tags:
    job_titles.append(i.text)
companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies_names=[]
for i in companies_tags:
    companies_names.append(i.text)
location_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']//span")
location=[]
for i in location_tags:
    location.append(i.text)
#fgetching urls:
urls=[]
for i in driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']"):
    urls.append(i.get_attribute("href"))


urls

In [38]:
job_title=[]
job_description=[]
for i in urls[0:10]:
    driver.get(i)
    #time.sleep(9)
    #fetching job title:
    try:
        job=driver.find_element_by_xpath("//h1[@class='av-special-heading-tag']")
        job_title.append(job.text.replace("/n","new line"))
    except:
        job_title.append('-')
        
    #fetching job description
    try:
        job_desc=driver.find_element_by_xpath("//div[@class='jdContainer job-desc']")
        job_description.append(job_desc.text)
    except:
        job_description.append('-')
        
job_title

['-', '-', '-', '-', '-', '-', '-', '-', '-', '-']

In [39]:
job_description

["LEAD DATA SCIENTIST BFSI\nFrom 5 to 9 year(s) of experience\n₹ Not Disclosed by Recruiter\nBengaluru\nApply on Company Website\nClicking apply will take you to the company’s website\nPosted: 2 days agoJob Applicants: 21Job Views: 542\nJob Description\nIntroduction\nSoftware Developers at IBM are the backbone of our strategic initiatives to design, code, test, and provide industry-leading solutions that make the world run today - planes and trains take off on time, bank transactions complete in the blink of an eye and the world remains safe because of the work our software developers do. Whether you are working on projects internally or for a client, software development is critical to the success of IBM and our clients worldwide. At IBM, you will use the latest software development tools, techniques and approaches and work with leading minds in the industry to build solutions you can be proud of.\n\nYour Role and Responsibilities\nIBM s Global Technology Services (GTS) business unit has embarked on a mission to be the most trusted partner to our clients and enable them with game changing technology backbone to drive competitive advantage. One of the most significant & challenging areas for our clients is Data. From identifying & capturing to curation & consumption - we would like to simplify, automate, and accelerate the data lifecycle within our client s myriad use cases.\nTo this effect we have launched specific offering(s) and are building out a team of passionate achievers to help us define, create, market & deliver data solutions to our clients. We are looking for a passionate Data Scientists with expertise in Machine Learning, who can contribute to deliver on this vision. This is a fun and fast paced environment, where developers are empowered to innovate and learn fast is our standard operating model.\nAs a Senior Data Scientist you will be at the forefront of this ride and get to work with end clients on a regular basis. You will be the face of GTS & evangelize the data science & ML solutions that we have to offer. You will create compelling value proposition and targeted content to significantly improve our chances of winning in the marketplace. You will defend IBM solutions and build trust with the client at all levels -operational to executive. You will help drive, qualify & close opportunities. You will be responsible for the execution and successful delivery of Data Science assignments. You will be responsible for identifying and supporting current and new hypotheses. With your understanding of complex concepts, you will translate hypotheses into actionable items that are understandable by non-technical business users. You understand challenges in the BFSI domains & can discover new avenues to apply AI/ML solutions to solve these challenges. The problems we address are significantly complex and we expect you to lead excellence in our data science methodologies. You have a distinct ability to identify and implement robust, efficient, and scalable solutions that leverage multiple techniques and/or technologies. You will Provide guidance and architecture support to platform development teams and oversee the development from initial concept to production deployment\n\nRequired Technical and Professional Expertise\nAs a leader in Data science organization, lead multiple scrum teams to deliver innovative ML solutions in BFSI space\nPH.D or Master s degree in a quantitative field such as computer science, applied mathematics, statistics, physics, engineering or finance\nOverall Data Science, Statistical Analysis, Data Analytics & Machine Learning experience of 10 years\n7 years of BFSI domain experience in implementing data science or AI solutions from exploration to production\n3 years of experience in a responsible senior or team lead role managing a team of data scientists who develop robust machine learning models to solve actual business problems\nExpert understanding of ML Production deployments. Have atleast 3 years of experience in production grade ML design, development & deployment\nWork closely with internal and external stakeholders, both technical and non-technical and help translate deep ML knowledge to stakeholders.\nWork closely with ML engineering/Infrastructure team to help define the vision of ML training and ML inference platforms running on Cloud as well as On-prem\nMentor and grow Junior data scientists in the team on both DS modelling and software engineering skills\nExpert ability to define Data Science model development & MLOps process, workflows, coding practices & DevOps practices\nExtensive overview of applied methods in statistics, machine learning and artificial intelligence\nExpert understanding of various AI/ML technology stacks including Cloud Based services\nHelp define the data science development workflows from coding and architecture best practices, data strategy, to ML training and Inference platforms\nDemonstrated experience in creating AI/ML solutions within the BFSI space:\nBanking: Credit, Risk, Customer Exp, Open Banking, Digital Banking, Cross-Sell, Up-Sell, Branch Ops, Treasury, Cards Business, SME Banking, Wealth Management\nInsurance/Insurtech: Claims, Operations, Agency Development, Sales & Distribution, Customer Experience, Forecasting, Actuarial, Segmentation, Pricing\nFS/Regtech: Compliance & Regulatory, Auto, STPI, Consumer Durables, Commercial, Mortgage\nKnowledge of software engineering practices such as version control, continuous delivery, unit testing, documentation, release management\nExperience in natural language processing, text analytics, data mining, text processing or other AI subdomains and techniques\nCoach and lead a team of other data scientists, engineers, and other stakeholders\nPropose suitable technology stacks for projects to be deployed across cloud platforms and on-premise infrastructure.\nSolid data management and statistical modelling skills:\nExperience with Scala/Python, Scikit-learn, TensorFlow, Keras, NLTK, PyTorch etc\nExperience with leveraging best practices conducting advanced analytics projects\nExperience in distributed & scalable ML development. Good PoV on TinyML and Embedded AI/ML\n\nPreferred Technical and Professional Expertise\nExperience with open-source distributed data processing & ML frameworks\nExperience working in a Linux environment\nExperience working within a development team setup which is building product/services\nExperience with presenting complex data science processes/information to non-data scientists\nExperience with Information Retrieval and relevant tools such as Lucene, Elasticsearch, Solr\nPrioritization skills; ability to manage ad-hoc requests in parallel with ongoing projects\nStrong experience in both classical ML modeling approaches and Deep learning based model approaches\nData analysis, reporting, visualization expertise and experience with tools such as Tableau, Alteryx, Python and R at scale\nGood NLP knowledge and cloud experience preferred\nPassion, Drive and Can-do attitude\nGood communication skills\nWillingness to thrive in ambiguous environments\nRole:Outside Consultant\nSalary: Not Disclosed by Recruiter\nIndustry:IT Services & Consulting\nFunctional Area:IT Software - Application Programming, Maintenance\nRole Category:Other\nEmployment Type:Full Time, Permanent\nKey Skills\nData analysisClaimsLinuxData managementWealth managementCodingData processingActuarialData miningForecasting\nEducation\nUG:Any Graduate\nPG:Any Postgraduate\nCompany Profile\nIBM India Pvt. Limited\nIBM has been present in India since 1992. IBM India's solutions and services span all major industries including financial services, healthcare, government, automotive, telecommunications and education, among others. As a trusted partner with wide-ranging service capabilities, IBM helps clients transform and succeed in challenging circumstances.\n\nIBM has been expanding its footprint in India - and has a presence in over 200 cities and towns across the country - either directly or through its strong business partner network. IBM India has clearly established itself as one of the leaders in the Indian Information Technology (IT) Industry - and continues to transform itself to align with global markets and geographies to grow this leadership position. Widely recognised as an employer of choice, IBM holds numerous awards for its industry-leading employment practices and policies.\n\nThe diversity and breadth of the entire IBM portfolio of research, consulting, solutions, services, systems and software, uniquely distinguishes IBM India from other companies in the industry.\n\nTo know more about business units at IBM India, click on the “About Us” link above.\nCompany Info\nView Contact Details\n+",
 "DATA SCIENTIST: ADVANCED ANALYTICS\nFrom 3 to 7 year(s) of experience\n₹ Not Disclosed by Recruiter\nBengaluru\nApply on Company Website\nClicking apply will take you to the company’s website\nPosted: 2 days agoJob Applicants: 53Job Views: 536\nJob Description\nIntroduction\nAs a Data Scientist at IBM, you will help transform our clients data into tangible business value by analyzing information, communicating outcomes and collaborating on product development. Work with Best in Class open source and visual tools, along with the most flexible and scalable deployment options. Whether it s investigating patient trends or weather patterns, you will work to solve real world problems for the industries transforming how we live.\n\nYour Role and Responsibilities\nWork with IBM Q Start team on active exploratory research engagements to prepare for future use case commercialization within specific industry\nEngage and educate client data science teams to define promising areas for quantum exploration\nImplement quantum approaches, which includes data pre-/post-processing, running numerics and visualizing data\nCollaborate with industry and solutioning experts to design and shape experiments to demonstrate quantum-enabled advantage\nDefine best practices related to information architecture, including collection, integration, organization, analysis and visualization of data for quantum-enabled impact\nEngage in practice development initiatives focused on building employee knowledge and skills in specific areas of expertise through coaching and development of training course material\n\nRequired Technical and Professional Expertise\nPhD/Masters in STEM-related fields with knowledge in Quantum Computing.\n5 years of data engineering and data science experience\n2 years of consulting experience within specific industries with strong domain expertise and business acumen\nProficiency with classical approaches to machine learning and linear algebra, including Support Vector Machine (SVM) for linear categorization and Singular Value Decomposition (SVD) to reduce dimensionality of data\nFamiliar with Qiskit software, including Qiskit Aqua for domain applications and Qiskit Terra for quantum circuit design and optimization\nExcellent ideation, facilitation and communications skills\nDetail-oriented team player with strong interpersonal skills and ability to take a leadership role when necessary\nWillingness to travel globally up to 40% once we return to a travel-safe environment.\nEnglish: Fluent\n\nPreferred Technical and Professional Expertise\n2 years of experience in at least one of the industries, with knowledge of industry trends, R&D areas, and computationally intensive processes (e.g. optimization)\nFamiliarity with Qiskit\nRole:Research Scientist\nSalary: Not Disclosed by Recruiter\nIndustry:IT Services & Consulting\nFunctional Area:Medical, Healthcare, R&D, Pharmaceuticals, Biotechnology\nRole Category:R&D\nEmployment Type:Full Time, Permanent\nKey Skills\nTrainingadvanced analyticsInterpersonal skillsdata scienceCircuit designingFocusConsultingMachine learningOpen sourceInformation architecture\nEducation\nUG:Any Graduate,B.Tech/B.E. in Computers\nPG:Any Postgraduate,M.Tech in Computers,MCA in Computers\nDoctorate:Ph.D/Doctorate in Computers\nCompany Profile\nIBM India Pvt. Limited\nIBM has been present in India since 1992. IBM India's solutions and services span all major industries including financial services, healthcare, government, automotive, telecommunications and education, among others. As a trusted partner with wide-ranging service capabilities, IBM helps clients transform and succeed in challenging circumstances.\n\nIBM has been expanding its footprint in India - and has a presence in over 200 cities and towns across the country - either directly or through its strong business partner network. IBM India has clearly established itself as one of the leaders in the Indian Information Technology (IT) Industry - and continues to transform itself to align with global markets and geographies to grow this leadership position. Widely recognised as an employer of choice, IBM holds numerous awards for its industry-leading employment practices and policies.\n\nThe diversity and breadth of the entire IBM portfolio of research, consulting, solutions, services, systems and software, uniquely distinguishes IBM India from other companies in the industry.\n\nTo know more about business units at IBM India, click on the “About Us” link above.\nCompany Info\nView Contact Details\n+",
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-']

In [40]:
#Q3 Data Scientist Pune and 0-3 lakhs
url="https://www.naukri.com/"
driver.get(url)
search=driver.find_element_by_id('qsb-keyword-sugg')
search.send_keys("Data Scientist")
search_btn=driver.find_element_by_xpath("//button[@class='btn']")
search_btn.click()

In [41]:
#locating the Pune filter
filter_btn=driver.find_element_by_xpath("//span[@title='Pune']")
filter_btn.click()

In [42]:
#locating the 0-3 lakhs filter
filter_btn_3lkh=driver.find_element_by_xpath("//span[@title='0-3 Lakhs']")
filter_btn_3lkh.click()

In [43]:
#getting tags for titles,companies,location) and then we will run a loop to iterate over the tags extracted above and extract the titles,companies,location text inside them

titles_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
job_titles=[]
for i in titles_tags:
    job_titles.append(i.text)
companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies_names=[]
for i in companies_tags:
    companies_names.append(i.text)
location_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']//span")
location=[]
for i in location_tags:
    location.append(i.text)
    
#now getting the tags for experience required and run a loop to iterate over the tags extracted
experience_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']//span")
experience_required=[]
for i in experience_tags:
    experience_required.append(i.text)
#creating the dataframe
import pandas as pd
jobs=pd.DataFrame({})
jobs['Title']=job_titles[0:10]
jobs['Location']=location[0:10]
jobs['Company']=companies_names[0:10]
jobs['Experience']=experience_required[0:10]

In [44]:
jobs #Q3 Data Scientist Pune and 0-3 lakhs

,Title,Location,Company,Experience
0,Job Opportunity For Data Scientist- Pune,Pune,MDINDIA HEALTH INSURANCE TPA PVT LTD,0-3 Yrs
1,Sr. Data Scientist,Pune,DATA AXLE SOLUTIONS PRIVATE LIMITED,5-10 Yrs
2,Lead Data Scientist,Pune,DATA AXLE SOLUTIONS PRIVATE LIMITED,7-12 Yrs
3,Opportunity with Accionlabs For Data Scientist,"Hyderabad/Secunderabad, Pune, Bangalore/Bengal...",Accion labs India Private Limited,3-5 Yrs
4,Data Scientist,Pune,Hire IT People,2-7 Yrs
5,Urgent Requirement For Sr. Data Scientist _Pune,Remote,Talent Sketchers,4-5 Yrs
6,Data Scientist,"Hyderabad/Secunderabad, Pune, Chennai, Bangalo...",ILABZ TECHNOLOGY LLP,3-5 Yrs
7,Trainee - Junior Data Analyst,(WFH during Covid),Cognizant Technology Solutions India Pvt Ltd,0-3 Yrs
8,Data Analyst,Pune,Edge Executive Search Pvt. Ltd.,0-2 Yrs
9,"Data Analyst, Quantitative Support Team","Pune, Bangalore/Bengaluru, Mumbai (All Areas)",TresVista,0-2 Yrs

In [45]:
url="https://www.glassdoor.co.in/member/home/index.htm"
driver.get(url)

In [46]:
#finding the html element for search box and put Data Scientist in the search box

search=driver.find_element_by_id('sc.keyword')
search.send_keys("Data Scientist")

In [47]:
#finding the html element for location  search box and put Noida as location

search_loc=driver.find_element_by_id('sc.location')
search_loc.send_keys("Noida")

In [48]:
#look for search button and click on it
search_btn=driver.find_element_by_xpath("//button[@class='gd-ui-button ml-std col-auto search__SearchStyles__newSearchButton css-1dqvyh7']")
search_btn.click()

In [49]:
#getting tags for companies and then we will run a loop to iterate over the tags extracted above and extract the companies text inside them

companies_tags=driver.find_elements_by_xpath("//a[@class=' job-search-key-l2wjgv e1n63ojh0 jobLink']//span")
companies_names=[]
for i in companies_tags:
    companies_names.append(i.text)

In [50]:
#same with days
days_tags=driver.find_elements_by_xpath("//div[@class='d-flex align-items-end pl-std css-17n8uzw']")
days=[]
for i in days_tags:
    days.append(i.text)

In [51]:
#same with rating
rating_tags=driver.find_elements_by_xpath("//span[@class=' job-search-key-srfzj0 e1cjmv6j0']")
rating=[]
for i in rating_tags:
    rating.append(i.text)

In [52]:
#creating dataframe
jobs=pd.DataFrame({})
jobs['Company Name']=companies_names[0:10]
jobs['Number days/hours of job posting']=days[0:10]
jobs['Rating of Company']=rating[0:10]
jobs #Q4 Data Scientist Noida

,Company Name,Number days/hours of job posting,Rating of Company
0,Liberin Technologies Private Limited,30d+,3.9
1,Noisy Lion,24h,3.5
2,AlgoScale Technologies Private Limited,15d,3.6
3,Grail Insights,1d,3.5
4,Lenskart,3d,3.8
5,Salasar New Age Technologies,30d+,3.9
6,Techlive,30d+,3.3
7,limeroad.com,15d,4.1
8,Grail Insights,1d,3.8
9,Genpact,2d,3.6

In [57]:
#accessing to the url glassdoor
url="https://www.glassdoor.co.in/Salaries/index.htm"
driver.get(url)

In [58]:
#finding the html element for search box and put Data Scientist in the search box

search=driver.find_element_by_id('KeywordSearch')
search.send_keys("Data Scientist")

In [59]:
#finding the html element for location search box and put NOida in the search box

search_loc=driver.find_element_by_id('LocationSearch')
search_loc.send_keys("Noida")

In [60]:
##finding the html element for search button and click on it

search_btn=driver.find_element_by_xpath("//button[@class='gd-btn-mkt']")
search_btn.click()

In [61]:
#finding the html element for min-max salary 

min_max_tgs=driver.find_elements_by_xpath("//div[@class='d-flex mt-xxsm css-79elbk epuxyqn0']/p")
minim_max_salary=[]                        
for i in min_max_tgs:
    minim_max_salary.append(i.text)
minim_max_salary

['₹4L',
 '₹13L',
 '₹1L',
 '₹28L',
 '₹6L',
 '₹23L',
 '₹5L',
 '₹1Cr',
 '₹4L',
 '₹17L',
 '₹8L',
 '₹16L',
 '₹8L',
 '₹20L',
 '₹10L',
 '₹18L',
 '₹5L',
 '₹15L',
 '₹6L',
 '₹16L',
 '₹4L',
 '₹13L',
 '₹2L',
 '₹19L',
 '₹4L',
 '₹21L',
 '₹6L',
 '₹17L',
 '₹10L',
 '₹21L',
 '₹8L',
 '₹21L',
 '₹10L',
 '₹30L',
 '₹9L',
 '₹15L',
 '₹12T',
 '₹64T',
 '₹5L',
 '₹73L']

In [63]:
min_=minim_max_salary[::2]

In [64]:
min_

['₹4L',
 '₹1L',
 '₹6L',
 '₹5L',
 '₹4L',
 '₹8L',
 '₹8L',
 '₹10L',
 '₹5L',
 '₹6L',
 '₹4L',
 '₹2L',
 '₹4L',
 '₹6L',
 '₹10L',
 '₹8L',
 '₹10L',
 '₹9L',
 '₹12T',
 '₹5L']

In [65]:
max_=minim_max_salary[1::2]
max_

['₹13L',
 '₹28L',
 '₹23L',
 '₹1Cr',
 '₹17L',
 '₹16L',
 '₹20L',
 '₹18L',
 '₹15L',
 '₹16L',
 '₹13L',
 '₹19L',
 '₹21L',
 '₹17L',
 '₹21L',
 '₹21L',
 '₹30L',
 '₹15L',
 '₹64T',
 '₹73L']

In [66]:
#getting companies tags and loop and iterate them to get the companies names
companies_tags=driver.find_elements_by_xpath("//a[@class='css-f3vw95 e1aj7ssy3']")
companies_names=[]
for i in companies_tags:
    companies_names.append(i.text)

In [67]:
#getting average tags and loop and iterate them to get the average salries

aveg_sal_tgs=driver.find_elements_by_xpath("//div[@class='col-12 col-lg-4 px-lg-0 d-flex align-items-baseline']//h3")
average_salary=[]
for i in aveg_sal_tgs:
    average_salary.append(i.text)

In [68]:
#getting company rating tags and loop and iterate them to get the company rating

rat_comp_tgs=driver.find_elements_by_xpath("//span[@class='m-0 css-kyx745']")
rating_comp=[]
for i in rat_comp_tgs:
    rating_comp.append(i.text)

In [69]:
#creating the dataframe with all the scrapped data.
jobs=pd.DataFrame({})
jobs['Company Name']=companies_names[0:10]
jobs['Minim Salary']=min_[0:10]
jobs['Maximum Salary']=max_[0:10]
jobs['Rating of Company']=rating_comp[0:10]
jobs['Average Salary']=average_salary[0:10]  
jobs #Q5 Data Scientist Noida

,Company Name,Minim Salary,Maximum Salary,Rating of Company,Average Salary
0,Tata Consultancy Services,₹4L,₹13L,3.9,"₹6,31,184"
1,IBM,₹1L,₹28L,3.9,"₹9,08,246"
2,Accenture,₹6L,₹23L,4.1,"₹11,93,390"
3,Delhivery,₹5L,₹1Cr,3.8,"₹12,49,716"
4,Ericsson-Worldwide,₹4L,₹17L,4,"₹7,58,335"
5,UnitedHealth Group,₹8L,₹16L,3.7,"₹12,80,000"
6,Optum,₹8L,₹20L,3.7,"₹13,55,086"
7,Optum Global Solutions,₹10L,₹18L,3.9,"₹14,55,430"
8,Valiance Solutions,₹5L,₹15L,4.2,"₹8,86,064"
9,EXL Service,₹6L,₹16L,3.6,"₹11,10,000"

In [45]:
#accessing url flipkart
url="https://www.flipkart.com/"
driver.get(url)

In [46]:
#find html element in order to click on the pop up and close it
driver.find_element_by_xpath("//button[@class='_2KpZ6l _2doB4z']").click()

In [47]:
#finding html element for search box and searching for "sunglasses"
search=driver.find_element_by_xpath("//input[@class='_3704LK']")
search.send_keys("sunglasses")

In [48]:
#finding html element for search button and click on it.
search_btn=driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_btn.click()

In [12]:
#downloading the libraries
from selenium.common.exceptions import StaleElementReferenceException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import time

In [10]:
#brand_names

In [50]:
#getting the data from flipkart website.
counter = 1
companies = []
description = []
prices = []
discounts = []
page_count = 1
columns = ["Company","Description","Price","Discount"]
while (counter <=100):
    products = driver.find_elements(By.XPATH,"//div[@class='_1xHGtK _373qXS']//div[@class='_2B099V']")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print(f"Products in page {page_count}: ",len(products))
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    for product in products:
        company = product.find_element(By.XPATH,".//div[@class='_2WkVRV']").text
        data_row = product.text.split("\n")
        
        try:
            desc = product.find_element(By.XPATH,".//a[@class='IRpwTa']").text
        except:
            desc = product.find_element(By.XPATH,".//a[@class='IRpwTa _2-ICcC']").text
        price = product.find_element(By.XPATH,".//div[@class='_30jeq3']").text
        try:
            discount = product.find_element(By.XPATH,".//div[@class='_3Ay6Sb']").text
            print(company)
            print(desc)
            print(price)
            print(discount)
            print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
            print(counter)
            print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
        except:
            discount = "-"
        if (counter>100):
            break
        else:
            counter += 1        
            companies.append(company)
            description.append(desc)
            prices.append(price)
            discounts.append(discount)
    page_count += 1
    driver.find_elements(By.XPATH,"//nav[@class='yFHi8N']/a")[-1].click()
    time.sleep(2)
print("Done Scraping!!!")

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Products in page 1:  40
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hipe
Mirrored, UV Protection, Gradient Round Sunglasses (55)
₹210
85% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PIRASO
UV Protection Aviator Sunglasses (Free Size)
₹331
79% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SHAAH COLLECTIONS
UV Protection, Polarized, Mirrored Rectangular Sunglass...
₹198
88% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PIRASO
UV Protection Aviator Sunglasses (54)
₹237
85% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Elligator
UV Protection Round Sunglasses (54)
₹295
88% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ROZZETTA CRAFT
UV Protection, Gradient Rectangular Sunglasses (Free Si...
₹404
79% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kingsunglasses
Mirrored, UV Protection Wayfarer Sunglasses (Free Size)
₹284
89% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Singco India
UV Protection, Riding Glasses, Others Aviator, Wayfarer...
₹225
67% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
8
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fastrack
Gradient, UV Protection Wayfarer Sunglasses (Free Size)
₹509
36% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
9
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PIRASO
UV Protection Aviator Sunglasses (54)
₹237
85% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kingsunglasses
UV Protection Round Sunglasses (54)
₹213
80% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Elligator
UV Protection Aviator, Round, Wayfarer Sunglasses (55)
₹266
86% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fastrack
UV Protection Wayfarer Sunglasses (Free Size)
₹859
4% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
13
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DEIXELS
UV Protection Aviator, Wayfarer Sunglasses (Free Size)
₹202
83% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SHAAH COLLECTIONS
UV Protection, Polarized, Mirrored Rectangular Sunglass...
₹215
78% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
15
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PIRASO
UV Protection Wayfarer Sunglasses (32)
₹237
85% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SHAAH COLLECTIONS
UV Protection Round Sunglasses (Free Size)
₹331
80% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
17
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PIRASO
UV Protection Aviator Sunglasses (54)
₹237
85% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kingsunglasses
Mirrored, UV Protection Wayfarer Sunglasses (Free Size)
₹284
89% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TheWhoop
UV Protection, Mirrored, Night Vision Shield Sunglasses...
₹285
74% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ROYAL SON
UV Protection Rectangular Sunglasses (58)
₹474
68% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
21
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUNBEE
UV Protection, Polarized, Mirrored Wayfarer Sunglasses ...
₹265
73% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
22
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fastrack
UV Protection Aviator Sunglasses (Free Size)
₹520
34% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
23
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Villain
Others Wayfarer Sunglasses (Free Size)
₹599
40% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
24
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PHENOMENAL
UV Protection Retro Square Sunglasses (Free Size)
₹379
81% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
25
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ROZZETTA CRAFT
UV Protection, Riding Glasses Rectangular Sunglasses (F...
₹449
79% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
26
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kingsunglasses
UV Protection, Mirrored Round Sunglasses (54)
₹236
80% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
27
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Sewell
Toughened Glass Lens Aviator Sunglasses (Free Size)
₹220
77% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
28
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fastrack
UV Protection Wayfarer Sunglasses (55)
₹359
60% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
29
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ROZZETTA CRAFT
UV Protection Retro Square Sunglasses (Free Size)
₹499
77% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
30
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Silver Kartz
UV Protection Wayfarer Sunglasses (Free Size)
₹246
83% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
31
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PIRASO
UV Protection Butterfly Sunglasses (64)
₹402
84% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
32
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fastrack
UV Protection Wayfarer Sunglasses (57)
₹499
37% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
33
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hipe
UV Protection, Gradient, Mirrored, Riding Glasses Aviat...
₹209
79% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
34
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Singco India
UV Protection Aviator Sunglasses (Free Size)
₹334
72% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
35
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PIRASO
UV Protection Aviator Sunglasses (54)
₹237
85% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
36
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kingsunglasses
UV Protection, Riding Glasses, Mirrored Wayfarer Sungla...
₹217
81% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
37
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ROYAL SON
Mirrored Aviator Sunglasses (55)
₹379
74% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
38
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PIRASO
UV Protection Butterfly Sunglasses (65)
₹449
82% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
39
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
NuVew
UV Protection, Mirrored Wayfarer, Rectangular Sunglasse...
₹375
64% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
40
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Products in page 2:  40
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PIRASO
UV Protection Aviator Sunglasses (58)
₹399
84% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
41
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OCCARIO
Others Round Sunglasses (52)
₹179
69% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
42
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Rich Club
UV Protection, Mirrored, Gradient Round Sunglasses (51)
₹215
73% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
43
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Elligator
UV Protection Round Sunglasses (54)
₹314
75% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
44
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Elligator
Mirrored Round Sunglasses (53)
₹312
87% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
45
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kingsunglasses
UV Protection Rectangular Sunglasses (55)
₹199
84% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
46
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUNBEE
UV Protection, Polarized, Mirrored Wayfarer Sunglasses ...
₹284
71% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
47
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Elligator
UV Protection Round Sunglasses (53)
₹295
88% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
48
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ROZZETTA CRAFT
UV Protection, Gradient Round Sunglasses (Free Size)
₹449
77% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
49
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GANSTA
UV Protection, Gradient Aviator Sunglasses (55)
₹289
85% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
50
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GANSTA
UV Protection, Night Vision, Riding Glasses Aviator Sun...
₹295
85% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
51
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ROYAL SON
Polarized, UV Protection Aviator Sunglasses (58)
₹711
64% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
52
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hipe
UV Protection, Night Vision, Gradient, Mirrored Round, ...
₹210
78% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
53
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HIPPON
UV Protection Wayfarer Sunglasses (55)
₹257
78% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
54
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kingsunglasses
UV Protection Round Sunglasses (Free Size)
₹331
79% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
55
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ROZZETTA CRAFT
UV Protection, Gradient Retro Square Sunglasses (Free S...
₹404
79% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
56
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Elligator
UV Protection Round Sunglasses (55)
₹266
86% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
57
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fastrack
UV Protection Aviator Sunglasses (Free Size)
₹695
13% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
58
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fastrack
UV Protection Wayfarer Sunglasses (Free Size)
₹854
5% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
59
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PIRASO
UV Protection Aviator Sunglasses (50)
₹331
79% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
60
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Singco
Mirrored Aviator Sunglasses (53)
₹239
76% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
61
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SRPM
UV Protection Wayfarer Sunglasses (53)
₹230
76% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
62
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PHENOMENAL
UV Protection, Mirrored Retro Square Sunglasses (53)
₹379
81% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
63
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PIRASO
UV Protection Aviator Sunglasses (Free Size)
₹331
79% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Singco India
UV Protection, Riding Glasses, Others Aviator, Wayfarer...
₹225
67% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
65
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Elligator
UV Protection, Riding Glasses Rectangular, Retro Square...
₹398
73% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
66
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PHENOMENAL
UV Protection Clubmaster Sunglasses (Free Size)
₹303
84% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
67
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PIRASO
UV Protection Aviator Sunglasses (58)
₹399
84% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
68
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PIRASO
UV Protection Aviator Sunglasses (Free Size)
₹331
79% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
69
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GANSTA
UV Protection Aviator Sunglasses (57)
₹284
85% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
70
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUNBEE
UV Protection, Polarized, Mirrored Wayfarer Sunglasses ...
₹314
75% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
71
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
AISLIN
UV Protection, Gradient Round, Cat-eye Sunglasses (60)
₹498
70% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
72
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hipe
UV Protection, Night Vision, Riding Glasses, Gradient, ...
₹199
84% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
73
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Silver Kartz
UV Protection Oval Sunglasses (56)
₹284
76% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
74
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
IRUS by IDEE
Gradient Rectangular Sunglasses (56)
₹389
69% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
75
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
NuVew
UV Protection, Night Vision, Riding Glasses, Polarized ...
₹375
77% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
76
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kingsunglasses
UV Protection Rectangular Sunglasses (Free Size)
₹197
83% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
77
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PHENOMENAL
UV Protection Round Sunglasses (53)
₹280
87% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
78
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Elligator
UV Protection, Riding Glasses Rectangular, Retro Square...
₹398
73% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
79
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
AISLIN
UV Protection, Gradient Oval Sunglasses (58)
₹495
67% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
80
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Products in page 3:  40
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ROYAL SON
UV Protection Over-sized Sunglasses (60)
₹664
66% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
81
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fastrack
UV Protection Aviator Sunglasses (58)
₹1,239
4% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
82
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kingsunglasses
UV Protection, Mirrored Round Sunglasses (Free Size)
₹260
84% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
83
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ROYAL SON
UV Protection Wayfarer Sunglasses (55)
₹248
80% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
84
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fastrack
UV Protection Aviator Sunglasses (58)
₹949
26% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
85
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Singco India
Riding Glasses, Others, UV Protection Wrap-around Sungl...
₹293
82% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
86
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
NuVew
UV Protection Aviator Sunglasses (58)
₹202
74% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
87
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DEIXELS
Polarized, UV Protection, Riding Glasses Wayfarer Sungl...
₹236
60% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
88
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GANSTA
Night Vision, Riding Glasses Wayfarer Sunglasses (53)
₹209
88% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
89
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fastrack
UV Protection Wayfarer Sunglasses (56)
₹369
58% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
90
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fravy
UV Protection Retro Square Sunglasses (Free Size)
₹284
81% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
91
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ROYAL SON
UV Protection Retro Square Sunglasses (58)
₹474
68% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
92
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kingsunglasses
Mirrored, UV Protection Wayfarer Sunglasses (53)
₹314
84% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
93
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hipe
UV Protection Sports Sunglasses (Free Size)
₹303
84% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
94
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
AISLIN
UV Protection, Gradient Cat-eye Sunglasses (61)
₹498
70% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
95
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Badfella
Polarized, UV Protection Retro Square Sunglasses (53)
₹255
74% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
96
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ROZZETTA CRAFT
Gradient, UV Protection Round Sunglasses (Free Size)
₹449
77% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
97
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
povty
UV Protection Wayfarer Sunglasses (Free Size)
₹349
65% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
98
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUNBEE
UV Protection, Polarized, Mirrored Retro Square Sunglas...
₹314
75% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
99
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Singco India
Mirrored, UV Protection, Riding Glasses, Others Wrap-ar...
₹331
83% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
100
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hipe
Mirrored, UV Protection, Gradient Round Sunglasses (55)
₹210
85% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
101
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Done Scraping!!!

In [51]:
#creting dataframe
import pandas as pd
sunglasses=pd.DataFrame({})
sunglasses['Sunglasses Brand Name']=companies[0:100]
sunglasses['Description']=description[0:100]
sunglasses['Price']=prices[0:100]
sunglasses['Discount %']=discounts[0:100]  
sunglasses #Q6 Sunglasses

,Sunglasses Brand Name,Description,Price,Discount %
0,hipe,"Mirrored, UV Protection, Gradient Round Sungla...",₹210,85% off
1,PIRASO,UV Protection Aviator Sunglasses (Free Size),₹331,79% off
2,SHAAH COLLECTIONS,"UV Protection, Polarized, Mirrored Rectangular...",₹198,88% off
3,PIRASO,UV Protection Aviator Sunglasses (54),₹237,85% off
4,Elligator,UV Protection Round Sunglasses (54),₹295,88% off
...,...,...,...,...
95,Badfella,"Polarized, UV Protection Retro Square Sunglass...",₹255,74% off
96,ROZZETTA CRAFT,"Gradient, UV Protection Round Sunglasses (Free...",₹449,77% off
97,povty,UV Protection Wayfarer Sunglasses (Free Size),₹349,65% off
98,SUNBEE,"UV Protection, Polarized, Mirrored Retro Squar...",₹314,75% off
99,Singco India,"Mirrored, UV Protection, Riding Glasses, Other...",₹331,83% off

In [80]:
#accesing url 
url="https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace"
driver.get(url)

In [81]:
#finding html element in order to click and close the pop up
driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']//span").click()

In [83]:
#gettin the data from flipkart
counter = 0
ratings = []
shrt_review = []
Full_review = []
data=[]
while(counter<100):
    reviews_deck = driver.find_elements(By.XPATH,"//div[@class='col _2wzgFH K0kLPL']")    
    for review in reviews_deck:
        if(counter>100):
            break
        else:
            counter+=1
        try:
            review.find_element(By.XPATH,".//div[@class='row']//span[@class='_1BWGvX']").click()
        except:
            pass
        finally:
            rating, review_desc = review.find_elements(By.XPATH,".//div[@class='row']")[:2]
            rating_stars, rating_desc = rating.text[0],rating.text[1:]
        rating_stars_ = rating_stars.strip()
        rating_desc_ = rating_desc.strip()
        review_desc_ = review_desc.text.strip()
        
        ratings.append(rating_stars_)
        shrt_review.append(rating_desc_)
        Full_review.append( review_desc_)
    try:
        driver.find_element(By.XPATH,"//a[@class='_1LKTO3'][2]/span").click()
        time.sleep(1)
    except:
        driver.find_element(By.XPATH,"//a[@class='_1LKTO3']/span").click()
        time.sleep(2)
print("Done Scraping!!!")

Done Scraping!!!

In [84]:
#creating the dataframe
import pandas as pd
iphone=pd.DataFrame({})
iphone['Rating']=ratings[0:100]
iphone['Short review']=shrt_review[0:100]
iphone['Full review']=Full_review[0:100]
  
iphone   #Q7 Iphone11

,Rating,Short review,Full review
0,5,Awesome,"Always love the apple products, upgraded from ..."
1,5,Perfect product!,Value for money\n5 star rating\nExcellent came...
2,1,Very poor,"Please DONT buy from here,\n\nI purchased Appl..."
3,5,Fabulous!,awesome phone to have. it has got many smart f...
4,5,Excellent,Its a fabulous mobile look awesome performance...
...,...,...,...
95,5,Fabulous!,Awesome mobile… Battery Backup is really impre...
96,3,Just okay,I have been using iphone 11 model since its la...
97,5,Just wow!,"Not mere a phone , Its more than that for fun ..."
98,4,Delightful,Received product before the delivery date perf...
99,5,Terrific purchase,Very good phone. All the apps are running smoo...

In [96]:
#importing the required libraries for selenium

!pip install selenium
import selenium
from selenium import webdriver

Requirement already satisfied: selenium in c:\users\bovi\anaconda3\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\bovi\anaconda3\lib\site-packages (from selenium) (1.26.4)

In [97]:
#conecting to the web driver
driver=webdriver.Chrome("chromedriver.exe")

In [98]:
#accesing the url
url="https://www.flipkart.com/"
driver.get(url)

In [99]:
#finding html element in order to closr the pop up
driver.find_element_by_xpath("//button[@class='_2KpZ6l _2doB4z']").click()

In [100]:
#gettin html element for search box and input "sneakers"
search=driver.find_element_by_xpath("//input[@class='_3704LK']")
search.send_keys("sneakers")

In [101]:
#checking the element for search button box and clicking on the seark button
search_btn=driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_btn.click()

In [102]:
#getting the data 
counter = 1
companies = []
description = []
prices = []
discounts = []
page_count = 1
columns = ["Company","Description","Price","Discount"]
while (counter <=100):
    products = driver.find_elements(By.XPATH,"//div[@class='_2B099V']")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print(f"Products in page {page_count}: ",len(products))
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    for product in products:
        company = product.find_element(By.XPATH,".//div[@class='_2WkVRV']").text
        data_row = product.text.split("\n")
        
        try:
            desc = product.find_element(By.XPATH,".//a[@class='IRpwTa']").text
        except:
            desc = product.find_element(By.XPATH,".//a[@class='IRpwTa _2-ICcC']").text
        price = product.find_element(By.XPATH,".//div[@class='_30jeq3']").text
        try:
            discount = product.find_element(By.XPATH,".//div[@class='_3Ay6Sb']").text
            print(company)
            print(desc)
            print(price)
            print(discount)
            print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
            print(counter)
            print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
        except:
            discount = "-"
        if (counter>100):
            break
        else:
            counter += 1        
            companies.append(company)
            description.append(desc)
            prices.append(price)
            discounts.append(discount)
    page_count += 1
    driver.find_elements(By.XPATH,"//nav[@class='yFHi8N']/a")[-1].click()
    time.sleep(2)
print("Done Scraping!!!")

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Products in page 1:  40
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
luxury fashion
Sneakers For Men
₹379
81% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DUCATI
Sneakers For Men
₹1,499
59% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Magnolia
Sneakers For Men
₹356
64% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BRUTON
Combo Pack Of 4 Casual Shoes Loafer Shoes Sneakers For ...
₹474
86% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Longwalk
Men Boxer Sneakers For Men
₹236
52% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Chevit
Perfect & Affordable Combo Pack of 02 Pairs Sneakers Ou...
₹599
66% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ASTEROID
Original Luxury Branded Fashionable Men's Casual Walkin...
₹499
75% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
India hub
Fashionable casual sneaker shoes Sneakers For Men
₹399
80% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
8
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
luxury fashion
Luxury Fashionable casual sneaker shoes Sneakers For Me...
₹379
70% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
9
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PEHANOSA
Sneakers For Men
₹375
62% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Creer
Sneakers For Men
₹398
60% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
luxury fashion
Luxury Fashionable casual sneaker shoes Sneakers For Me...
₹379
87% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BIRDE
Birde Trendy Casual Shoes Sneakers For Men
₹359
28% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
13
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Numenzo
White Sneaker For Men Sneakers For Men
₹429
66% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Numenzo
Numenzo Black Sneaker For Men Sneakers For Men
₹449
65% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
15
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Echor
Mens Walking Running Shoes - Lightweight Breathable Mes...
₹399
60% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Shoes Bank
White Sneaker For Men's/Boy's Sneakers For Men
₹349
65% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
17
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RODDICK SHOES
Fashion Outdoor Canvas Casual Light Weight Lace-up Even...
₹474
52% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
World Wear Footwear
5011-Latest Collection Stylish Casual Loafer Sneakers S...
₹240
51% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
India hub
Sneakers For Men
₹379
70% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Kraasa
Series 7 Sneakers For Men
₹444
55% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
21
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Absolute comfort
SOFT Sneakers For Men
₹198
60% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
22
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
believe
Sneakers for men(black_6) Sneakers For Men
₹449
55% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
23
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PROVOGUE
Sneakers For Men
₹789
64% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
24
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ASTEROID
Original Luxury Branded Fashionable Men's Casual Walkin...
₹499
50% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
25
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Airland
shoe Sneakers For Men
₹264
47% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
26
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SCATCHITE
Sneakers Sneakers For Men
₹398
60% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
27
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DUCATI
Sneakers For Men
₹1,259
65% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
28
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Numenzo
Sneakers For Men
₹449
77% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
29
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Numenzo
Sneakers For Men
₹398
60% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
30
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Arohi
Sneakers For Men
₹460
53% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
31
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
luxury fashion
luxury fashionable casual shoes Sneakers For Men
₹399
80% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
32
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HOC
Luxury Fashionable Breathable Casual Sneakers Shoes For...
₹378
81% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
33
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
restinfoot
Casual shoes,Sneakers for men's,shoes for men's Sneaker...
₹349
65% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
34
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
VIPSJAZZY
Sneakers For Men
₹379
62% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
35
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Nilatin
Black Sneaker For Men Sneakers For Men
₹449
65% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
36
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Robbie jones
Sneakers For Men
₹499
50% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
37
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RODDICK SHOES
Fashion Outdoor Canvas Casual Light Weight Lace-up Even...
₹474
52% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
38
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bluemaker
casual for men (blue 10) Sneakers For Men
₹449
55% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
39
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BAUCHHAAR
Sneakers For Men
₹448
55% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
40
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Products in page 2:  40
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
World Wear Footwear
Men 5014 Latest Collection Stylish Casual Sports Loafer...
₹240
51% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
41
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SHOEFLY
Combo Men Pack of 2 Loafers Shoes Sneakers For Men
₹362
72% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
42
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RODDICK SHOES
Fashion Outdoor Canvas Casual Light Weight Lace-up Even...
₹474
52% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
43
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
luxury fashion
Sneakers For Men
₹379
81% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
44
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SPARX
SM-322 Sneakers For Men
₹769
23% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
45
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SPARX
SM439G Sneakers For Men
₹649
7% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
46
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Kreverse
Sneakers For Men
₹266
73% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
47
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
luxury fashion
Luxury Fashionable casual sneaker shoes Sneakers For Me...
₹379
70% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
48
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Axter
New Collection of Combo Pack of 2 Stylish Shoes Sneaker...
₹599
39% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
49
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BIRDE
Combo Pack of 2 Casual Shoes Sneakers For Men
₹472
52% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
50
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SHOEFLY
Combo Men Pack of 2 Loafers Shoes Sneakers For Men
₹362
63% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
51
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DUCATI
Sneakers For Men
₹1,499
59% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
52
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D-SNEAKERZ
Casual , Partywear Sneakers Shoes For Men's And Boys Wh...
₹348
47% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
53
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BRUTON
Modern & Trendy Collection Combo Pack of 02 Shoes for M...
₹444
82% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
54
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BIRDE
Birde Trendy Casual Shoes Sneakers For Men
₹283
43% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
55
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
India hub
Fashionable casual sneaker shoes Sneakers For Men
₹399
80% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
56
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Chevit
Unique & Perfect Collection Combo Pack of 02 Shoes for ...
₹599
60% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
57
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bluemaker
casual for men (beige 06) Sneakers For Men
₹449
55% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
58
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SPARX
Men White Sneakers Sneakers For Men
₹623
16% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
59
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
luxury fashion
Luxury Fashionable casual sneaker shoes Sneakers For Me...
₹379
87% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
60
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Zorth
New Fashion Outdoor Trendy Lightweight Casual,Canvas St...
₹435
56% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
61
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BRUTON
Lightweight Pack Of 1 Trendy Sneakers Sneakers Sneakers...
₹168
71% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
62
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jack Diamond
Sneakers For Men
₹627
37% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
63
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Echor
Mens Walking Running Shoes - Lightweight Breathable Mes...
₹399
60% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
India hub
Fashionable sneaker casual shoes Sneakers For Men
₹379
81% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
65
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jack Diamond
Canvas Sneaker Sneakers For Men
₹630
36% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
66
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BIRDE
Men's Stylish Casual Shoes Sneakers For Men
₹283
43% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
67
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
India hub
Sneakers For Men
₹379
70% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
68
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Zsyto
Sneakers For Men
₹398
69% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
69
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Chevit
Smart Casuals Canvas Shoes Combo pack of 2 Sneakers For...
₹399
60% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
70
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SPARX
SM-482 Sneakers For Men
₹998
26% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
71
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PROVOGUE
Sneakers For Men
₹789
64% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
72
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SPARX
SM-675 Sneakers For Men
₹745
17% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
73
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Labbin
Casual Sneakers White Shoes For Men And Boys Sneakers F...
₹399
60% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
74
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Robbie jones
Casual Sneakers Shoes For Men Sneakers For Men
₹399
60% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
75
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DUCATI
Sneakers For Men
₹1,259
65% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
76
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Magnolia
White Sneakers Sneakers For Men
₹311
68% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
77
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TR
Sneakers For Men
₹499
75% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
78
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Robbie jones
Sneakers For Men
₹499
50% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
79
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
India hub
Sneakers For Men
₹399
80% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
80
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Products in page 3:  40
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PUMA
Kor Sneakers For Men
₹1,400
64% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
81
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BIRDE
Birde Trendy Casual Shoes Sneakers For Men
₹283
43% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
82
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Kraasa
Shark-41 Sneakers For Men
₹444
55% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
83
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Peelu
Sneakers For Men
₹442
55% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
84
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SPARX
SM-162 Sneakers For Men
₹849
10% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
85
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Zorth
Sneakers For Men
₹439
56% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
86
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SHOEFLY
Combo Men Pack of 2 Loafers Shoes Sneakers For Men
₹362
63% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
87
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Clymb
Perfect Sports Shoes for Running Training Hiking Footba...
₹599
53% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
88
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Rising Wolf
Sneakers For Men
₹569
64% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
89
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
T-ROCK
Synthetic Leather Casual Partywear Wedding Sneakers Sho...
₹379
62% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
90
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bluemaker
casual shoe for men Sneakers For Men
₹449
55% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
91
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Echor
Raptor Sneakers For Men
₹429
57% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
92
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
KANEGGYE
Sneakers For Men
₹399
20% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
93
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SPARX
SM-607 Sneakers For Men
₹660
17% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
94
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WRIZT
Girls Running, Walking, Sports Shoes Walking Shoes Snea...
₹445
55% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
95
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Clymb
Perfect Sports Shoes for Running Training Hikking & Gym...
₹449
55% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
96
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Edoeviv
Luxury Branded Fashionable Men's Casual Walking Partywe...
₹499
37% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
97
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BIRDE
Trendy Casual Shoes Sneakers For Men
₹283
43% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
98
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SPARX
Casual Sneakers Sneakers For Men
₹1,000
23% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
99
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
STRANGER BROTHERS
Sneakers For Men
₹449
55% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
100
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BRUTON
Combo Pack Of 2 Casual Shoes Sneakers Shoes Sneakers Fo...
₹499
80% off
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
101
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Done Scraping!!!

In [103]:
#creting dataframe
import pandas as pd
sneaker=pd.DataFrame({})
sneaker['Sneaker Brand Name']=companies[0:100]
sneaker['Description']=description[0:100]
sneaker['Price']=prices[0:100]
sneaker['Discount %']=discounts[0:100]  
sneaker  #Q8 Sneakers

,Sneaker Brand Name,Description,Price,Discount %
0,luxury fashion,Sneakers For Men,₹379,81% off
1,DUCATI,Sneakers For Men,"₹1,499",59% off
2,Magnolia,Sneakers For Men,₹356,64% off
3,BRUTON,Combo Pack Of 4 Casual Shoes Loafer Shoes Snea...,₹474,86% off
4,Longwalk,Men Boxer Sneakers For Men,₹236,52% off
...,...,...,...,...
95,Clymb,Perfect Sports Shoes for Running Training Hikk...,₹449,55% off
96,Edoeviv,Luxury Branded Fashionable Men's Casual Walkin...,₹499,37% off
97,BIRDE,Trendy Casual Shoes Sneakers For Men,₹283,43% off
98,SPARX,Casual Sneakers Sneakers For Men,"₹1,000",23% off
99,STRANGER BROTHERS,Sneakers For Men,₹449,55% off

In [143]:
#getting url
url="https://www.myntra.com/shoes"
driver.get(url)

In [144]:
#apply price filter
filter_btn=driver.find_elements_by_xpath("//label[@class='common-customCheckbox vertical-filters-label']//div[@class='common-checkboxIndicator']")
for i in filter_btn:
    if i.text=='Rs. 6897 to Rs. 13595':
        i.click()
        break

In [145]:
#apply price filter
filter_btn=driver.find_elements_by_xpath("//label[@class='common-customCheckbox']//div[@class='common-checkboxIndicator']")
for i in filter_btn:
    if i.text=='Black':
        i.click()
        break

In [146]:
#getting the data
counter = 1
companies = []
description = []
prices = []
page_count = 1
columns = ["Company","Description","Price","Discount"]
while (counter <=100):
    products = driver.find_elements(By.XPATH,"//div[@class='product-productMetaInfo']")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print(f"Products in page {page_count}: ",len(products))
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    for product in products:
        company = product.find_element(By.XPATH,"//div[@class='product-productMetaInfo']//h3[@class='product-brand']").text
        data_row = product.text.split("\n")
        
        try:
            desc = product.find_element(By.XPATH,"//div[@class='product-productMetaInfo']//h4[@class='product-product']").text
        except:
            desc = product.find_element(By.XPATH,".//a[@class='IRpwTa _2-ICcC']").text
        price = product.find_element(By.XPATH,".//div[@class='product-price']//span").text
        if (counter>100):
            break
        else:
            counter += 1        
            companies.append(company)
            description.append(desc)
            prices.append(price)
    page_count += 1
    
    
    try:
        driver.find_elements(By.XPATH,"//li[@class='pagination-active']//a")[-1].click()
        time.sleep(1)
    except:
        driver.find_elements(By.XPATH,"//li[@class='pagination-number']//a")[-1].click()
        time.sleep(2)
    
    
    time.sleep(2)
print("Done Scraping!!!")

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Products in page 1:  50
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Products in page 2:  50
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Done Scraping!!!

In [147]:
#creting dataframe
import pandas as pd
sneaker=pd.DataFrame({})
sneaker['Shoes Brand Name']=companies[0:100]
sneaker['Description']=description[0:100]
sneaker['Price']=prices[0:100]
  
sneaker #Q9 Shoes from myntra

   Shoes Brand Name                     Description               Price
0              Puma  Men BlackTraining or Gym Shoes            Rs. 6999
1              Puma  Men BlackTraining or Gym Shoes            Rs. 6999
2              Puma  Men BlackTraining or Gym Shoes    Rs. 8099Rs. 8999
3              Puma  Men BlackTraining or Gym Shoes    Rs. 8999Rs. 9999
4              Puma  Men BlackTraining or Gym Shoes           Rs. 10999
..              ...                             ...                 ...
95             Puma                                            Rs. 6999
96             Puma                                            Rs. 7999
97             Puma                                  Rs. 10355Rs. 10900
98             Puma                                  Rs. 11199Rs. 13999
99             Puma                                           Rs. 12999

[100 rows x 3 columns]

In [180]:
#getting amazon link
url="https://www.amazon.in/"
driver.get(url)

In [181]:
#find element html in order to send keys "Laptop"
search=driver.find_element_by_id('twotabsearchtextbox')
search.send_keys("Laptop")

In [182]:
#finding the htm button and click on search btn 
search_btn=driver.find_element_by_xpath("//input[@id='nav-search-submit-button']")
search_btn.click()

In [183]:
#locating the core i7 filter
filter_btn=driver.find_elements_by_xpath("//a[@class='a-link-normal s-navigation-item']/span")
for i in filter_btn:
    if i.text=='Intel Core i7':
        i.click()
        break

In [184]:
#locating the core i7 filter
filter_btn=driver.find_elements_by_xpath("//a[@class='a-link-normal s-navigation-item']/span")
for i in filter_btn:
    if i.text=='Intel Core i9':
        i.click()
        break

In [185]:
#getting the titles
titl_tgs=driver.find_elements_by_xpath("//span[@class='a-size-medium a-color-base a-text-normal']")
titles=[]                        
for i in titl_tgs:
    titles.append(i.text)
titles

['HP Envy 11th Gen Core i7 Processor 13.3-inch (33.78 cms) FHD Touchscreen Laptop (16GB/1TB SSD/Win 10/NVIDIA MX450 2GB/Natural Silver/1.3 kg), 13-ba1018TX',
 'Mi Notebook Horizon Edition 14 Intel Core i7-10510U 10th Gen Thin and Light Laptop(8GB/512GB SSD/Windows 10/Nvidia MX350 2GB Graphics/Grey/1.35Kg)(Without Webcam) XMA1904-AF',
 'Lenovo IdeaPad S540 11th Gen Intel Core i7 13.3" QHD IPS Thin & Light Laptop (16GB/512GB SSD/Windows 10/MS Office 2019/Intel Iris Xe Graphics/Iron Grey/1.28Kg), 82H1002CIN',
 'ASUS ROG G703GI-E5148T 17.3" (43.94 cms) FHD 144Hz/3ms Gaming Laptop (8th Gen Intel Core i9-8950HK/64GB/2TB SSHD + 1.5TB NVMe SSD/Windows 10/GTX 1080 8GB Graphics/4.70 Kg), Aluminum',
 'ASUS TUF Dash F15 (2021), 15.6-inch (39.62 cms) FHD 144Hz, Intel Core i7-11370H 11th Gen, RTX 3050 4GB Graphics Gaming Laptop (16GB RAM/512GB SSD/Windows 10/White/2 kg), FX516PC-HN062T',
 'ASUS TUF Dash F15 (2021), 15.6-inch (39.62 cms) FHD 144Hz, Intel Core i7-11370H 11th Gen, RTX 3050 4GB Graphics Gaming Laptop (16GB RAM/512GB SSD/Windows 10/Gray/2 kg), FX516PC-HN063T',
 'Fujitsu UH-X 11th Gen Intel Core i7 13.3” (33.78cm) FHD IPS 400Nits 2-in1 Touch Convertible Laptop (16GB/1TB SSD/Win10/Office/Iris Xe Graphics/Backlit Kb/Black/997gms), 4ZR1D71993',
 'HP Pavilion 13(2021) 11th Gen Intel Core i7 Laptop, 16GB RAM, 1TB SSD, 13.3-inch(33.8 cm) FHD Screen, Win 10, MS Office, Ceramic White, 1.24 Kg (13-bb0078TU)',
 'Lenovo IdeaPad Flex 5 11th Gen Intel Core i7 14"(35.56cm) FHD IPS 2-in-1 Touchscreen Laptop(16GB/512GB SSD/Windows 10/MS Office/Lenovo Digital Pen/Fingerprint Reader/Graphite Grey/1.5Kg), 82HS0092IN',
 'MSI GF75 Thin, Intel i7-10750H, 17.3" (43.9 cm) FHD IPS-Level 144Hz Panel Laptop (8GB/512GB NVMe SSD/Windows 10 Home/Nvidia GTX1650 4GB GDDR6/Black/2.2Kg), 10SCXR-654IN',
 'Lenovo IdeaPad Gaming 3 11th Gen Intel Core i7-11370H 15.6" (39.63cm) FHD IPS Gaming Laptop (8GB/512GB SSD/Windows 10/NVIDIA RTX 3050 4GB/120Hz Refresh Display/Shadow Black/2.25Kg), 82K1004EIN',
 'Lenovo IdeaPad Gaming 3 Intel Core i7 10th Gen 15.6" FHD IPS 250Nits Gaming Laptop (8GB/512GB SSD/Win10/NVIDIA GTX 1650 4GB GDDR6 Graphics/120Hz/Onyx Black/2.2Kg), 81Y4019EIN',
 'Dell 14 (2021) i7-1165G7 2in1 Touch Screen Laptop, 16Gb RAM, 512Gb SSD, 14” (35.56 cms) FHD Display, Win 10 + MSO, Backlit KB + FPR + Active Pen, Silver Metal Color (Inspiron 5410, D560469WIN9S)',
 'Acer Swift 5 14" (35.56cms) Full HD IPS Display with Touchscreen Ultra Thin and Light Notebook (Intel i7 - 11th Gen/16GB RAM/1TB SSD/Win10/Intel Iris Xe Graphics/1.05 Kg/Mist Green), SF514-55TA',
 'Lenovo Yoga 7 11th Gen Intel Core i7-1165G7 14" (35.56cm) FHD IPS 2-in-1 Touchscreen Laptop (16GB/512GB SSD/Windows 10/MS Office/Lenovo Digital Pen/Fingerprint Reader/Slate Grey/1.43Kg), 82BH004HIN',
 'Lenovo Legion 7 10th Gen Intel Core i9 15.6 inch Full HD Gaming Laptop (16GB/1TB SSD/Windows 10/MS Office 2019/144 Hz/NVIDIA RTX 2080 8GB GDDR6 Graphics/Slate Grey/2.25Kg), 81YU006HIN',
 'HP Pavilion (2021) Thin & Light 11th Gen Core i7 Laptop, 16 GB RAM, 1TB SSD, Iris Xe Graphics, 14" (35.56cms) FHD Screen, Windows 10, MS Office, Backlit Keyboard (14-dv0058TU)',
 'HP Envy 11th Gen Core i7 Processor 13.3-inch (33.78 cms) FHD Touchscreen Laptop (16GB/1TB SSD/Win 10/NVIDIA MX450 2GB/Natural Silver/1.3 kg), 13-ba1018TX',
 'Lenovo Legion Y540 9th Gen Intel Core i7-9750HF 15.6" (39.63cm) FHD IPS Gaming Laptop (8GB/1TB + 256GB SSD/Windows 10/NVIDIA GTX 1650 4GB/60Hz Refresh Display/Raven Black/2.3Kg), 81SY00U7IN',
 'ASUS VivoBook S S14 Intel Core i7-1165G7 11th Gen, 14-inch FHD Thin and Light Laptop (8GB RAM/512GB SSD + 32GB Optane Memory/Windows 10/Office 2019/Iris X Graphics- Indie Black/1.4 Kg), S433EA-AM701TS',
 '(Renewed) Hp Intel 4th Gen Core i7 15.6-inch (39.56 Cms) 1920 x 1080 Laptop (32GB RAM /1TB SSD/Windows 10 Pro/MS Office/NVIDIA Graphics/ Gray/2.5kg) HP ZBook 15 Mobile Workstation',
 '(Renewed) Hp Intel 7th Gen Core i7 13.3-inch (33.78 Cms) 1920 x 1080 TOUCHSCREEN Laptop (16GB RAM/1TB SSD/Windows 10 Pro/MS Office/Intel HD Integrated Graphics/ Silver/1.2Kg) EliteBook x360 G2',
 'ASUS ZenBook 13 OLED (2021) Intel Core i7-1165G7 11th Gen 14" (35.56cms) FHD Thin and Light Laptop (16GB/1TB SSD/Windows 10/Office 2019/Intel Iris Xᵉ Graphics/Lilac Mist/1.14 kg), UX325EA-KG701TS',
 'Acer Nitro 5 Core i7 11th Gen 15.6" (39.62cms) Full HD IPS Gaming Laptop (16 GB/256GB SSD/1 TB HDD/Win 10/4 GB Graphics/NVIDIA GeForce RTX 3050 Ti/144 Hz, Black, 2.4 kg) AN515-57',
 'HP Pavilion x360 (2021) 14" (35.56cms) FHD Touchscreen Laptop, 11th Gen Core i7, 8 GB RAM, 512GB SSD, 2-in-1 Convertible, Windows 10, MS Office, Finger Print Reader (14-dw1040TU)',
 '(Renewed) Hp Intel 4th Gen Core i7 15.6-inch (39.56 Cms) 1920 x 1080 Laptop (8GB RAM/256GB SSD/Windows 10 Pro/MS Office/NVIDIA Graphics/ Gray/2.5kg) HP ZBook 15 Mobile Workstation']

In [186]:
#getting the price
prc_tgs=driver.find_elements_by_xpath("//span[@class='a-price-whole']")
prices=[]                        
for i in prc_tgs:
    prices.append(i.text)
prices

['1,23,350',
 '57,990',
 '77,990',
 '5,56,524',
 '85,990',
 '84,990',
 '1,07,990',
 '92,990',
 '98,500',
 '74,990',
 '84,990',
 '73,990',
 '94,999',
 '1,19,499',
 '1,99,990',
 '1,23,350',
 '72,990',
 '81,290',
 '53,999',
 '63,999',
 '1,01,910',
 '1,05,227',
 '41,999']

In [178]:
#fgetching urls:
urls=[]
for i in driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a"):
    urls.append(i.get_attribute("href"))
urls

['https://www.amazon.in/gp/slredirect/picassoRedirect.html/ref=pa_sp_atf_computers_sr_pg1_1?ie=UTF8&adId=A10081262K6KZOZ37JXYV&url=%2FHP-Processor-13-3-inch-Touchscreen-13-ba1018TX%2Fdp%2FB091FJ13Q5%2Fref%3Dsr_1_1_sspa%3Fdchild%3D1%26keywords%3DLaptop%26qid%3D1631551765%26refinements%3Dp_n_feature_thirteen_browse-bin%253A12598163031%257C16757432031%26rnid%3D12598141031%26s%3Dcomputers%26sr%3D1-1-spons%26psc%3D1&qualifier=1631551765&id=8626863352737621&widgetName=sp_atf',
 'https://www.amazon.in/Notebook-Horizon-i7-10510U-Graphics-XMA1904-AF/dp/B089DFJHZ8/ref=sr_1_2?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-2',
 'https://www.amazon.in/Lenovo-IdeaPad-Windows-Graphics-82H1002CIN/dp/B094XJPQ6N/ref=sr_1_3?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-3',
 'https://www.amazon.in/Asus-G703GI-E5148T-17-3-inch-i9-8950HK-Processor/dp/B07GRCW51K/ref=sr_1_4?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-4',
 'https://www.amazon.in/ASUS-Dash-F15-15-6-inch-i7-11370H-FX516PC-HN062T/dp/B096KZ11KK/ref=sr_1_5?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-5',
 'https://www.amazon.in/ASUS-Dash-F15-15-6-inch-i7-11370H-FX516PC-HN063T/dp/B096KVJ5PC/ref=sr_1_6?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-6',
 'https://www.amazon.in/Fujitsu-33-78cm-Convertible-Graphics-4ZR1D71993/dp/B098P4M233/ref=sr_1_7?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-7',
 'https://www.amazon.in/HP-Pavilion-13-3-inch-Ceramic-13-bb0078TU/dp/B09839P9XB/ref=sr_1_8?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-8',
 'https://www.amazon.in/MSI-i7-10750H-IPS-Level-Windows-10SCXR-654IN/dp/B093L8QGL7/ref=sr_1_9?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-9',
 'https://www.amazon.in/Lenovo-Touchscreen-Fingerprint-Graphite-82HS0092IN/dp/B08WRZQBQ6/ref=sr_1_10?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-10',
 'https://www.amazon.in/Lenovo-IdeaPad-i7-11370H-39-63cm-82K1004EIN/dp/B09BJ7GD7B/ref=sr_1_11?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-11',
 'https://www.amazon.in/Lenovo-IdeaPad-250Nits-Graphics-81Y4019EIN/dp/B097TZMG7R/ref=sr_1_12?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-12',
 'https://www.amazon.in/Dell-i7-1165G7-Inspiron-5410-D560469WIN9S/dp/B095S9NJ4S/ref=sr_1_13?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-13',
 'https://www.amazon.in/gp/slredirect/picassoRedirect.html/ref=pa_sp_mtf_computers_sr_pg1_1?ie=UTF8&adId=A00766773MSMG2AO2CGIQ&url=%2FAcer-Swift-Display-Touchscreen-Notebook%2Fdp%2FB08M41DHTV%2Fref%3Dsr_1_14_sspa%3Fdchild%3D1%26keywords%3DLaptop%26qid%3D1631551765%26refinements%3Dp_n_feature_thirteen_browse-bin%253A12598163031%257C16757432031%26rnid%3D12598141031%26s%3Dcomputers%26sr%3D1-14-spons%26psc%3D1&qualifier=1631551765&id=8626863352737621&widgetName=sp_mtf',
 'https://www.amazon.in/Lenovo-Touchscreen-Fingerprint-Aluminium-82BH004HIN/dp/B08P3M22QQ/ref=sr_1_15?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-15',
 'https://www.amazon.in/HP-Pavilion-Graphics-35-56cms-14-dv0058TU/dp/B08WB857GB/ref=sr_1_16?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-16',
 'https://www.amazon.in/HP-Processor-13-3-inch-Touchscreen-13-ba1018TX/dp/B091FJ13Q5/ref=sr_1_17?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-17',
 'https://www.amazon.in/Lenovo-i7-9750HF-39-63cm-Windows-81SY00U7IN/dp/B092MRQCJ6/ref=sr_1_18?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-18',
 'https://www.amazon.in/ASUS-VivoBook-i7-1165G7-Graphics-S433EA-AM701TS/dp/B08PQTZB3Z/ref=sr_1_19?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-19',
 'https://www.amazon.in/15-6-inch-HP-ZBook-15-Workstation/dp/B09DQ4DZ5N/ref=sr_1_20?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-20',
 'https://www.amazon.in/Lenovo-Legion-Windows-Graphics-81YU006HIN/dp/B08GG9RZJC/ref=sr_1_21?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-21',
 'https://www.amazon.in/13-3-inch-TOUCHSCREEN-Integrated-Graphics-EliteBook/dp/B09CMZLGYG/ref=sr_1_22?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-22',
 'https://www.amazon.in/ASUS-i7-1165G7-35-56cms-Graphics-UX325EA-KG701TS/dp/B095C55Q7P/ref=sr_1_23?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-23',
 'https://www.amazon.in/Acer-39-62cms-Graphics-GeForce-AN515-57/dp/B09C8HZMW2/ref=sr_1_24?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-24',
 'https://www.amazon.in/HP-Pavilion-Touchscreen-Convertible-14-dw1040TU/dp/B08R843NHL/ref=sr_1_25?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-25',
 'https://www.amazon.in/LifeDigital-Laptop-Intel%C2%AE-Storage-Windows/dp/B08HRHFV23/ref=sr_1_26?dchild=1&keywords=Laptop&qid=1631551765&refinements=p_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&rnid=12598141031&s=computers&sr=1-26']

In [189]:
#fgetching urls:

rating=[]
for i in urls[0:10]:
    driver.get(i)
    #time.sleep(9)
    #fetching job title:
    try:
        rat_tg=driver.find_element_by_xpath("//span[@class='a-size-medium a-color-base']")
        rating.append(rat_tg.text.replace("/n","new line"))
    except:
        rating.append('-')
        
        
rating

['4.1 out of 5',
 '4.2 out of 5',
 '4.3 out of 5',
 '3.7 out of 5',
 '-',
 '3 out of 5',
 '4.1 out of 5',
 '5 out of 5',
 '4.1 out of 5',
 '4 out of 5']

In [193]:
#creating dataframe
import pandas as pd
laptop=pd.DataFrame({})
laptop['Laptop title']=titles[0:10]
laptop['Price']=prices[0:10]
laptop['Rating']=rating[0:10]
  
laptop #Q9 Laptop fro amazon

                                        Laptop title     Price        Rating
0  HP Envy 11th Gen Core i7 Processor 13.3-inch (...  1,23,350  4.1 out of 5
1  Mi Notebook Horizon Edition 14 Intel Core i7-1...    57,990  4.2 out of 5
2  Lenovo IdeaPad S540 11th Gen Intel Core i7 13....    77,990  4.3 out of 5
3  ASUS ROG G703GI-E5148T 17.3" (43.94 cms) FHD 1...  5,56,524  3.7 out of 5
4  ASUS TUF Dash F15 (2021), 15.6-inch (39.62 cms...    85,990             -
5  ASUS TUF Dash F15 (2021), 15.6-inch (39.62 cms...    84,990    3 out of 5
6  Fujitsu UH-X 11th Gen Intel Core i7 13.3” (33....  1,07,990  4.1 out of 5
7  HP Pavilion 13(2021) 11th Gen Intel Core i7 La...    92,990    5 out of 5
8  Lenovo IdeaPad Flex 5 11th Gen Intel Core i7 1...    98,500  4.1 out of 5
9  MSI GF75 Thin, Intel i7-10750H, 17.3" (43.9 cm...    74,990    4 out of 5

In [ ]:
#Got it :)